{
//=========Macro generated from canvas: Canvas2_200_400/Canvas2_200_400
//=========  (Sat Jan  3 16:42:04 2015) by ROOT version5.34/05
   TCanvas *Canvas2_200_400 = new TCanvas("Canvas2_200_400", "Canvas2_200_400",0,22,600,800);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Canvas2_200_400->SetHighLightColor(2);
   Canvas2_200_400->Range(0,0,1,1);
   Canvas2_200_400->SetFillColor(0);
   Canvas2_200_400->SetBorderMode(0);
   Canvas2_200_400->SetBorderSize(2);
   Canvas2_200_400->SetTickx(1);
   Canvas2_200_400->SetTicky(1);
   Canvas2_200_400->SetLeftMargin(0.16);
   Canvas2_200_400->SetRightMargin(0.05);
   Canvas2_200_400->SetTopMargin(0.05);
   Canvas2_200_400->SetBottomMargin(0.13);
   Canvas2_200_400->SetFrameFillStyle(0);
   Canvas2_200_400->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad3
   TPad *pad3 = new TPad("pad3", "pad3",0,0.3,1,1);
   pad3->Draw();
   pad3->cd();
   pad3->Range(-4.917721,-0.5,3.943038,0.5526316);
   pad3->SetFillColor(0);
   pad3->SetBorderMode(0);
   pad3->SetBorderSize(2);
   pad3->SetTickx(1);
   pad3->SetTicky(1);
   pad3->SetLeftMargin(0.16);
   pad3->SetRightMargin(0.05);
   pad3->SetTopMargin(0.05);
   pad3->SetBottomMargin(0);
   pad3->SetFrameFillStyle(0);
   pad3->SetFrameBorderMode(0);
   pad3->SetFrameFillStyle(0);
   pad3->SetFrameBorderMode(0);
   
   TProfile *Jet pT Balance with RECO (raw) = new TProfile("Jet pT Balance with RECO (raw)","Jet pT Balance with RECO (raw)",28,-3.5,3.5,"");
   Jet pT Balance with RECO (raw)->SetBinEntries(5,2);
   Jet pT Balance with RECO (raw)->SetBinEntries(6,3);
   Jet pT Balance with RECO (raw)->SetBinEntries(7,3);
   Jet pT Balance with RECO (raw)->SetBinEntries(8,8);
   Jet pT Balance with RECO (raw)->SetBinEntries(9,10);
   Jet pT Balance with RECO (raw)->SetBinEntries(10,7);
   Jet pT Balance with RECO (raw)->SetBinEntries(11,6);
   Jet pT Balance with RECO (raw)->SetBinEntries(12,8);
   Jet pT Balance with RECO (raw)->SetBinEntries(13,9);
   Jet pT Balance with RECO (raw)->SetBinEntries(14,6);
   Jet pT Balance with RECO (raw)->SetBinEntries(15,2);
   Jet pT Balance with RECO (raw)->SetBinEntries(16,3);
   Jet pT Balance with RECO (raw)->SetBinEntries(17,11);
   Jet pT Balance with RECO (raw)->SetBinEntries(18,10);
   Jet pT Balance with RECO (raw)->SetBinEntries(19,3);
   Jet pT Balance with RECO (raw)->SetBinEntries(20,8);
   Jet pT Balance with RECO (raw)->SetBinEntries(21,5);
   Jet pT Balance with RECO (raw)->SetBinEntries(22,4);
   Jet pT Balance with RECO (raw)->SetBinEntries(23,3);
   Jet pT Balance with RECO (raw)->SetBinContent(5,0.0400526);
   Jet pT Balance with RECO (raw)->SetBinContent(6,-0.2128286);
   Jet pT Balance with RECO (raw)->SetBinContent(7,-0.1603154);
   Jet pT Balance with RECO (raw)->SetBinContent(8,-0.1195948);
   Jet pT Balance with RECO (raw)->SetBinContent(9,-0.4567308);
   Jet pT Balance with RECO (raw)->SetBinContent(10,-0.6381641);
   Jet pT Balance with RECO (raw)->SetBinContent(11,0.09397791);
   Jet pT Balance with RECO (raw)->SetBinContent(12,-0.4866497);
   Jet pT Balance with RECO (raw)->SetBinContent(13,-0.1184495);
   Jet pT Balance with RECO (raw)->SetBinContent(14,-0.2550824);
   Jet pT Balance with RECO (raw)->SetBinContent(15,0.1406256);
   Jet pT Balance with RECO (raw)->SetBinContent(16,-0.1426382);
   Jet pT Balance with RECO (raw)->SetBinContent(17,-0.6482955);
   Jet pT Balance with RECO (raw)->SetBinContent(18,-0.9868881);
   Jet pT Balance with RECO (raw)->SetBinContent(19,-0.4193808);
   Jet pT Balance with RECO (raw)->SetBinContent(20,-0.5125969);
   Jet pT Balance with RECO (raw)->SetBinContent(21,-0.4042102);
   Jet pT Balance with RECO (raw)->SetBinContent(22,-0.2029136);
   Jet pT Balance with RECO (raw)->SetBinContent(23,-0.2413442);
   Jet pT Balance with RECO (raw)->SetBinError(5,0.03250832);
   Jet pT Balance with RECO (raw)->SetBinError(6,0.1579403);
   Jet pT Balance with RECO (raw)->SetBinError(7,0.1491351);
   Jet pT Balance with RECO (raw)->SetBinError(8,0.2417987);
   Jet pT Balance with RECO (raw)->SetBinError(9,0.5484932);
   Jet pT Balance with RECO (raw)->SetBinError(10,0.3048723);
   Jet pT Balance with RECO (raw)->SetBinError(11,0.1166106);
   Jet pT Balance with RECO (raw)->SetBinError(12,0.2295293);
   Jet pT Balance with RECO (raw)->SetBinError(13,0.3033662);
   Jet pT Balance with RECO (raw)->SetBinError(14,0.1222499);
   Jet pT Balance with RECO (raw)->SetBinError(15,0.1052563);
   Jet pT Balance with RECO (raw)->SetBinError(16,0.1608839);
   Jet pT Balance with RECO (raw)->SetBinError(17,0.2930369);
   Jet pT Balance with RECO (raw)->SetBinError(18,0.3579726);
   Jet pT Balance with RECO (raw)->SetBinError(19,0.2776623);
   Jet pT Balance with RECO (raw)->SetBinError(20,0.2916384);
   Jet pT Balance with RECO (raw)->SetBinError(21,0.245406);
   Jet pT Balance with RECO (raw)->SetBinError(22,0.1131923);
   Jet pT Balance with RECO (raw)->SetBinError(23,0.1531295);
   Jet pT Balance with RECO (raw)->SetMinimum(-0.5);
   Jet pT Balance with RECO (raw)->SetMaximum(0.5);
   Jet pT Balance with RECO (raw)->SetEntries(111);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   Jet pT Balance with RECO (raw)->SetLineColor(ci);
   Jet pT Balance with RECO (raw)->SetLineStyle(0);

   ci = TColor::GetColor("#000099");
   Jet pT Balance with RECO (raw)->SetMarkerColor(ci);
   Jet pT Balance with RECO (raw)->SetMarkerStyle(20);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetTitle("eta");
   Jet pT Balance with RECO (raw)->GetXaxis()->SetRange(1,28);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetTitleOffset(0.9);
   Jet pT Balance with RECO (raw)->GetXaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetTitle("#frac{probe_jet_pT - ref_jet_pT}{probe_jet_pT + ref_jet_pT}");
   Jet pT Balance with RECO (raw)->GetYaxis()->CenterTitle(true);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetTitleOffset(1.6);
   Jet pT Balance with RECO (raw)->GetYaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)->GetZaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)->GetZaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)->GetZaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)->GetZaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)->Draw("hist e1");
   
   TProfile *Jet pT Balance with RECO vs HLT (raw) = new TProfile("Jet pT Balance with RECO vs HLT (raw)","Jet pT Balance with RECO vs HLT (raw)",28,-3.5,3.5,"");
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(5,2);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(6,3);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(7,3);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(8,8);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(9,10);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(10,7);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(11,6);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(12,8);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(13,9);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(14,6);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(15,2);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(16,3);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(17,11);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(18,10);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(19,3);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(20,8);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(21,5);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(22,4);
   Jet pT Balance with RECO vs HLT (raw)->SetBinEntries(23,3);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(5,0.0544799);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(6,-0.2580902);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(7,-0.1870546);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(8,-0.1873302);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(9,-0.5241025);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(10,-0.7399262);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(11,0.008811377);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(12,-0.4931507);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(13,-0.1735165);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(14,-0.2677818);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(15,0.139644);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(16,-0.1476145);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(17,-0.8146874);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(18,-1.025585);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(19,-0.4078658);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(20,-0.5719316);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(21,-0.4181798);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(22,-0.2353206);
   Jet pT Balance with RECO vs HLT (raw)->SetBinContent(23,-0.2695497);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(5,0.05208275);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(6,0.1789901);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(7,0.1635251);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(8,0.2421278);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(9,0.5622693);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(10,0.3387024);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(11,0.1165045);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(12,0.244853);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(13,0.3246594);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(14,0.1316509);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(15,0.1039795);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(16,0.166353);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(17,0.3800575);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(18,0.3602295);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(19,0.2740194);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(20,0.2960102);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(21,0.2410494);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(22,0.1246407);
   Jet pT Balance with RECO vs HLT (raw)->SetBinError(23,0.1707201);
   Jet pT Balance with RECO vs HLT (raw)->SetMinimum(-0.5);
   Jet pT Balance with RECO vs HLT (raw)->SetMaximum(0.5);
   Jet pT Balance with RECO vs HLT (raw)->SetEntries(111);

   ci = TColor::GetColor("#990000");
   Jet pT Balance with RECO vs HLT (raw)->SetLineColor(ci);
   Jet pT Balance with RECO vs HLT (raw)->SetLineStyle(0);

   ci = TColor::GetColor("#990000");
   Jet pT Balance with RECO vs HLT (raw)->SetMarkerColor(ci);
   Jet pT Balance with RECO vs HLT (raw)->SetMarkerStyle(20);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetRange(1,28);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetLabelFont(42);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetTitleOffset(0.9);
   Jet pT Balance with RECO vs HLT (raw)->GetXaxis()->SetTitleFont(42);
   Jet pT Balance with RECO vs HLT (raw)->GetYaxis()->SetLabelFont(42);
   Jet pT Balance with RECO vs HLT (raw)->GetYaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO vs HLT (raw)->GetYaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO vs HLT (raw)->GetYaxis()->SetTitleOffset(1.6);
   Jet pT Balance with RECO vs HLT (raw)->GetYaxis()->SetTitleFont(42);
   Jet pT Balance with RECO vs HLT (raw)->GetZaxis()->SetLabelFont(42);
   Jet pT Balance with RECO vs HLT (raw)->GetZaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO vs HLT (raw)->GetZaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO vs HLT (raw)->GetZaxis()->SetTitleFont(42);
   Jet pT Balance with RECO vs HLT (raw)->Draw("hist e1 same");
   
   TLegend *leg = new TLegend(0.4,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Jet pT Balance with RECO (raw)","Jet pT Balance with RECO (raw)","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Jet pT Balance with RECO vs HLT (raw)","Jet pT Balance with RECO vs HLT (raw)","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#990000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#990000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   leg->Draw();
   pad3->Modified();
   Canvas2_200_400->cd();
  
// ------------>Primitives in pad: pad4
   pad4 = new TPad("pad4", "pad4",0,0,1,0.3);
   pad4->Draw();
   pad4->cd();
   pad4->Range(-4.917721,-0.3529412,3.943038,2);
   pad4->SetFillColor(0);
   pad4->SetBorderMode(0);
   pad4->SetBorderSize(2);
   pad4->SetTickx(1);
   pad4->SetTicky(1);
   pad4->SetLeftMargin(0.16);
   pad4->SetRightMargin(0.05);
   pad4->SetTopMargin(0);
   pad4->SetBottomMargin(0.15);
   pad4->SetFrameFillStyle(0);
   pad4->SetFrameBorderMode(0);
   pad4->SetFrameFillStyle(0);
   pad4->SetFrameBorderMode(0);
   
   TH1D *Jet pT Balance with RECO (raw)_px = new TH1D("Jet pT Balance with RECO (raw)_px","Jet pT Balance with RECO (raw)",28,-3.5,3.5);
   Jet pT Balance with RECO (raw)_px->SetBinContent(5,0.7351813);
   Jet pT Balance with RECO (raw)_px->SetBinContent(6,0.8246287);
   Jet pT Balance with RECO (raw)_px->SetBinContent(7,0.8570514);
   Jet pT Balance with RECO (raw)_px->SetBinContent(8,0.6384172);
   Jet pT Balance with RECO (raw)_px->SetBinContent(9,0.8714532);
   Jet pT Balance with RECO (raw)_px->SetBinContent(10,0.86247);
   Jet pT Balance with RECO (raw)_px->SetBinContent(11,10.66552);
   Jet pT Balance with RECO (raw)_px->SetBinContent(12,0.9868173);
   Jet pT Balance with RECO (raw)_px->SetBinContent(13,0.6826412);
   Jet pT Balance with RECO (raw)_px->SetBinContent(14,0.9525758);
   Jet pT Balance with RECO (raw)_px->SetBinContent(15,1.007029);
   Jet pT Balance with RECO (raw)_px->SetBinContent(16,0.966289);
   Jet pT Balance with RECO (raw)_px->SetBinContent(17,0.7957598);
   Jet pT Balance with RECO (raw)_px->SetBinContent(18,0.9622685);
   Jet pT Balance with RECO (raw)_px->SetBinContent(19,1.028232);
   Jet pT Balance with RECO (raw)_px->SetBinContent(20,0.8962556);
   Jet pT Balance with RECO (raw)_px->SetBinContent(21,0.9665942);
   Jet pT Balance with RECO (raw)_px->SetBinContent(22,0.8622857);
   Jet pT Balance with RECO (raw)_px->SetBinContent(23,0.8953608);
   Jet pT Balance with RECO (raw)_px->SetBinError(5,0.5563605);
   Jet pT Balance with RECO (raw)_px->SetBinError(6,0.4982108);
   Jet pT Balance with RECO (raw)_px->SetBinError(7,0.8410301);
   Jet pT Balance with RECO (raw)_px->SetBinError(8,1.498356);
   Jet pT Balance with RECO (raw)_px->SetBinError(9,1.348118);
   Jet pT Balance with RECO (raw)_px->SetBinError(10,0.3363095);
   Jet pT Balance with RECO (raw)_px->SetBinError(11,141.5058);
   Jet pT Balance with RECO (raw)_px->SetBinError(12,0.4617793);
   Jet pT Balance with RECO (raw)_px->SetBinError(13,2.141155);
   Jet pT Balance with RECO (raw)_px->SetBinError(14,0.3539408);
   Jet pT Balance with RECO (raw)_px->SetBinError(15,0.3410047);
   Jet pT Balance with RECO (raw)_px->SetBinError(16,1.323331);
   Jet pT Balance with RECO (raw)_px->SetBinError(17,0.3899427);
   Jet pT Balance with RECO (raw)_px->SetBinError(18,0.2255563);
   Jet pT Balance with RECO (raw)_px->SetBinError(19,0.4856093);
   Jet pT Balance with RECO (raw)_px->SetBinError(20,0.523805);
   Jet pT Balance with RECO (raw)_px->SetBinError(21,0.5301893);
   Jet pT Balance with RECO (raw)_px->SetBinError(22,0.26115);
   Jet pT Balance with RECO (raw)_px->SetBinError(23,0.3314548);
   Jet pT Balance with RECO (raw)_px->SetMinimum(0);
   Jet pT Balance with RECO (raw)_px->SetMaximum(2);
   Jet pT Balance with RECO (raw)_px->SetEntries(0.03493305);
   Jet pT Balance with RECO (raw)_px->SetLineStyle(0);
   Jet pT Balance with RECO (raw)_px->SetMarkerStyle(20);
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetTitle("eta");
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetTitleOffset(0.9);
   Jet pT Balance with RECO (raw)_px->GetXaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetTitle("#frac{probe_jet_pT - ref_jet_pT}{probe_jet_pT + ref_jet_pT}");
   Jet pT Balance with RECO (raw)_px->GetYaxis()->CenterTitle(true);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetTitleOffset(1.6);
   Jet pT Balance with RECO (raw)_px->GetYaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)_px->GetZaxis()->SetLabelFont(42);
   Jet pT Balance with RECO (raw)_px->GetZaxis()->SetLabelOffset(0.007);
   Jet pT Balance with RECO (raw)_px->GetZaxis()->SetLabelSize(0.035);
   Jet pT Balance with RECO (raw)_px->GetZaxis()->SetTitleFont(42);
   Jet pT Balance with RECO (raw)_px->Draw("hist e1");
   pad4->Modified();
   Canvas2_200_400->cd();
   Canvas2_200_400->Modified();
   Canvas2_200_400->cd();
   Canvas2_200_400->SetSelected(Canvas2_200_400);
}
