{
//=========Macro generated from canvas: rms_balance_eta_1_/rms_balance_eta_1_
//=========  (Thu Jan  8 09:51:36 2015) by ROOT version5.34/05
   TCanvas *rms_balance_eta_1_ = new TCanvas("rms_balance_eta_1_", "rms_balance_eta_1_",11,73,600,300);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   rms_balance_eta_1_->SetHighLightColor(2);
   rms_balance_eta_1_->Range(-304.4354,-0.1743902,1598.286,1.167073);
   rms_balance_eta_1_->SetFillColor(0);
   rms_balance_eta_1_->SetBorderMode(0);
   rms_balance_eta_1_->SetBorderSize(2);
   rms_balance_eta_1_->SetTickx(1);
   rms_balance_eta_1_->SetTicky(1);
   rms_balance_eta_1_->SetLeftMargin(0.16);
   rms_balance_eta_1_->SetRightMargin(0.05);
   rms_balance_eta_1_->SetTopMargin(0.05);
   rms_balance_eta_1_->SetBottomMargin(0.13);
   rms_balance_eta_1_->SetFrameFillStyle(0);
   rms_balance_eta_1_->SetFrameBorderMode(0);
   rms_balance_eta_1_->SetFrameFillStyle(0);
   rms_balance_eta_1_->SetFrameBorderMode(0);
   
   TGraph *graph = new TGraph(13);
   graph->SetName("Graph");
   graph->SetTitle("dijet_balance_rms_per_mean1_1");
   graph->SetFillColor(1);
   graph->SetMarkerStyle(21);
   graph->SetPoint(0,100,0);
   graph->SetPoint(1,300,0);
   graph->SetPoint(2,500,0);
   graph->SetPoint(3,700,0);
   graph->SetPoint(4,900,0);
   graph->SetPoint(5,1100,0);
   graph->SetPoint(6,1300,0);
   graph->SetPoint(7,1650,0);
   graph->SetPoint(8,2150,0);
   graph->SetPoint(9,2650,0);
   graph->SetPoint(10,3150,0);
   graph->SetPoint(11,3650,0);
   graph->SetPoint(12,4150,0);
   
   TH1F *Graph_Graph7 = new TH1F("Graph_Graph7","dijet_balance_rms_per_mean1_1",100,0,4555);
   Graph_Graph7->SetMinimum(0);
   Graph_Graph7->SetMaximum(1.1);
   Graph_Graph7->SetDirectory(0);
   Graph_Graph7->SetStats(0);
   Graph_Graph7->SetLineStyle(0);
   Graph_Graph7->SetMarkerStyle(20);
   Graph_Graph7->GetXaxis()->SetTitle("pT");
   Graph_Graph7->GetXaxis()->SetRange(1,33);
   Graph_Graph7->GetXaxis()->SetLabelFont(42);
   Graph_Graph7->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph7->GetXaxis()->SetTitleFont(42);
   Graph_Graph7->GetYaxis()->SetTitle("RMS/MEAN");
   Graph_Graph7->GetYaxis()->SetLabelFont(42);
   Graph_Graph7->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetYaxis()->SetTitleOffset(1.6);
   Graph_Graph7->GetYaxis()->SetTitleFont(42);
   Graph_Graph7->GetZaxis()->SetLabelFont(42);
   Graph_Graph7->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetZaxis()->SetTitleFont(42);
   graph->SetHistogram(Graph_Graph7);
   
   graph->Draw("ap");
   
   graph = new TGraph(13);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);
   graph->SetMarkerColor(2);
   graph->SetMarkerStyle(21);
   graph->SetPoint(0,100,0);
   graph->SetPoint(1,300,0);
   graph->SetPoint(2,500,0);
   graph->SetPoint(3,700,0);
   graph->SetPoint(4,900,0);
   graph->SetPoint(5,1100,0);
   graph->SetPoint(6,1300,0);
   graph->SetPoint(7,1650,0);
   graph->SetPoint(8,2150,0);
   graph->SetPoint(9,2650,0);
   graph->SetPoint(10,3150,0);
   graph->SetPoint(11,3650,0);
   graph->SetPoint(12,4150,0);
   
   TH1F *Graph_Graph8 = new TH1F("Graph_Graph8","Graph",100,0,4555);
   Graph_Graph8->SetMinimum(0);
   Graph_Graph8->SetMaximum(1.1);
   Graph_Graph8->SetDirectory(0);
   Graph_Graph8->SetStats(0);
   Graph_Graph8->SetLineStyle(0);
   Graph_Graph8->SetMarkerStyle(20);
   Graph_Graph8->GetXaxis()->SetTitle("pT");
   Graph_Graph8->GetXaxis()->SetLabelFont(42);
   Graph_Graph8->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph8->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph8->GetXaxis()->SetTitleFont(42);
   Graph_Graph8->GetYaxis()->SetTitle("RMS/MEAN");
   Graph_Graph8->GetYaxis()->SetLabelFont(42);
   Graph_Graph8->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph8->GetYaxis()->SetTitleOffset(1.6);
   Graph_Graph8->GetYaxis()->SetTitleFont(42);
   Graph_Graph8->GetZaxis()->SetLabelFont(42);
   Graph_Graph8->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph8->GetZaxis()->SetTitleFont(42);
   graph->SetHistogram(Graph_Graph8);
   
   graph->Draw("p");
   
   graph = new TGraph(13);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);
   graph->SetMarkerColor(3);
   graph->SetMarkerStyle(21);
   graph->SetPoint(0,100,0);
   graph->SetPoint(1,300,0);
   graph->SetPoint(2,500,0);
   graph->SetPoint(3,700,0);
   graph->SetPoint(4,900,0);
   graph->SetPoint(5,1100,0);
   graph->SetPoint(6,1300,0);
   graph->SetPoint(7,1650,0);
   graph->SetPoint(8,2150,0);
   graph->SetPoint(9,2650,0);
   graph->SetPoint(10,3150,0);
   graph->SetPoint(11,3650,0);
   graph->SetPoint(12,4150,0);
   
   TH1F *Graph_Graph9 = new TH1F("Graph_Graph9","Graph",100,0,4555);
   Graph_Graph9->SetMinimum(0);
   Graph_Graph9->SetMaximum(1.1);
   Graph_Graph9->SetDirectory(0);
   Graph_Graph9->SetStats(0);
   Graph_Graph9->SetLineStyle(0);
   Graph_Graph9->SetMarkerStyle(20);
   Graph_Graph9->GetXaxis()->SetTitle("pT");
   Graph_Graph9->GetXaxis()->SetLabelFont(42);
   Graph_Graph9->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph9->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph9->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph9->GetXaxis()->SetTitleFont(42);
   Graph_Graph9->GetYaxis()->SetTitle("RMS/MEAN");
   Graph_Graph9->GetYaxis()->SetLabelFont(42);
   Graph_Graph9->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph9->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph9->GetYaxis()->SetTitleOffset(1.6);
   Graph_Graph9->GetYaxis()->SetTitleFont(42);
   Graph_Graph9->GetZaxis()->SetLabelFont(42);
   Graph_Graph9->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph9->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph9->GetZaxis()->SetTitleFont(42);
   graph->SetHistogram(Graph_Graph9);
   
   graph->Draw("p");
   
   TLegend *leg = new TLegend(0.6,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","nPVzbins_0_7","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","nPVzbins_7_15","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","nPVzbins_15_25","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(3);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0,0.9502941,0.2263758,0.99,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(10);
   TText *text = pt->AddText("dijet_balance_rms_per_mean1_1");
   pt->Draw();
   rms_balance_eta_1_->Modified();
   rms_balance_eta_1_->cd();
   rms_balance_eta_1_->SetSelected(rms_balance_eta_1_);
}
