ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MZPL,MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ
     $ ,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MM,MDL_MZPH

      COMMON/MASSES/ MDL_MZPL,MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ
     $ ,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MM,MDL_MZPH


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WZPL,MDL_WZPH,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WZPL,MDL_WZPH,MDL_WH


      DOUBLE COMPLEX GC_10

      COMMON/COUPLINGS/ GC_10

